### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by lyssieth** [KarlitosVII/trilogy-save-editor#7]
How feasible is supporting Linux in this?

Since ME:LE (and other ME games) runs over Proton (currently with a lot of patches required) and some people may prefer Linux over Windows for their gaming, a save editor might be wanted for them (and me) as well.

**Comment by lyssieth** [comment]
I tested it out myself, not much needs to be changed, just finding the path where the saves are will be harder.

**Comment by rkfg** [comment]
The newest version doesn't work in Linux at all. Building with `cargo build --release`, running results in:
```
thread 'main' panicked at 'cannot call wasm-bindgen imported functions on non-wasm targets', /home/rkfg/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.55/src/lib.rs:5412:9
stack backtrace:
   0:     0x55c3e98ca8d2 - std::backtrace_rs::backtrace::libunwind::trace::hc6c3491277866fea
                               at /rustc/c1026539bd22e9d070988deaa47b1360cbc76436/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55c3e98ca8d2 - std::backtrace_rs::backtrace::trace_unsynchronized::h4524f073368a5b13
                               at /rustc/c1026539bd22e9d070988deaa47b1360cbc76436/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55c3e98ca8d2 - std::sys_common::backtrace::_print_fmt::h0d0cace6159902af
                               at /rustc/c1026539bd22e9d070988deaa47b1360cbc76436/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55c3e98ca8d2 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e6af6f05919a7fc
                               at /rustc/c1026539bd22e9d070988deaa47b1360cbc76436/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55c3e98bb57c - core::fmt::write::h72801a82c94e6ff1
                               at /rustc/c1026539bd22e9d070988deaa47b1360cbc76436/library/core/src/fmt/mod.rs:1163:17
   5:     0x55c3e98ca044 - std::io::Write::write_fmt::ha4f5d34aaccbac84
                               at /rustc/c1026539bd22e9d070988deaa47b1360cbc76436/library/std/src/io/mod.rs:1696:15
   6:     0x55c3e98c9e7d - std::sys_common::backtrace::_print::heed69f5ce9a8e189
                               at /rustc/c1026539bd22e9d070988deaa47b1360cbc76436/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55c3e98c9e7d - std::sys_common::backtrace::print::h5f3918bd80c09252
                               at /rustc/c1026539bd22e9d070988deaa47b1360cbc76436/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55c3e98c9e7d - std::panicking::default_hook::{{closure}}::h5af30648530eb3d0
                               at /rustc/c1026539bd22e9d070988deaa47b1360cbc76436/library/std/src/panicking.rs:210:50
   9:     0x55c3e98c9e7d - std::panicking::default_hook::he88d5fb1ba1b4c19
                               at /rustc/c1026539bd22e9d070988deaa47b1360cbc76436/library/std/src/panicking.rs:227:9
  10:     0x55c3e98c9e7d - std::panicking::rust_panic_with_hook::h01febc308b2b313b
                               at /rustc/c1026539bd22e9d070988deaa47b1360cbc76436/library/std/src/panicking.rs:624:17
  11:     0x55c3e98be7e4 - std::panicking::begin_panic::{{closure}}::h87691649b21e80eb
  12:     0x55c3e98be7b6 - std::sys_common::backtrace::__rust_end_short_backtrace::h0ab8b79393471d8a
  13:     0x55c3e98b8a76 - std::panicking::begin_panic::h38be7af48290afa0
  14:     0x55c3e98be799 - js_sys::global::get_global_object::h448da0085bf9188c
  15:     0x55c3e98be8ff - std::thread::local::fast::Key<T>::try_initialize::h1187296d7d39e704
  16:     0x55c3e98be801 - std::thread::local::LocalKey<T>::with::h3f097bd0e22ab9e2
  17:     0x55c3e98be776 - js_sys::global::h5d8e48d270fce6b8
  18:     0x55c3e98ea056 - trilogy_save_editor::main::h41480e2e4154978f
  19:     0x55c3e98e9383 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf1cbd0c01137d6c9
  20:     0x55c3e98e9892 - main
  21:     0x7fc0126b2e4a - __libc_start_main
                               at ./csu/../csu/libc-start.c:314:16
  22:     0x55c3e98ba20a - _start
  23:                0x0 - <unknown>
```

Compiling with `cargo build --release --target wasm32-unknown-unknown` results in `trilogy-save-editor.wasm` that can't be launched by itself. Any suggestions?

**Comment by KarlitosVII** [comment]
As mentioned in readme:

```
npm update
cargo install make
cargo make release
```

I didn't test linux version myself but CI doesn't complain.

**Comment by rkfg** [comment]
Tried this first, it says this:
```
> cargo install make
    Updating crates.io index
error: there is nothing to install in `make v0.0.0`, because it has no binaries
`cargo install` is only for installing programs, and can't be used with libraries.
To use a library crate, add it as a dependency in a Cargo project instead.
> cargo make release
error: no such subcommand: `make`

        Did you mean `miri`?
```

```
> rustup toolchain list
stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default) (override)
```
There's also `wasm32-unknown-unknown (installed)` in `rustup target list`. I'm not familiar with Rust ecosystem so not sure what this all means.

**Comment by KarlitosVII** [comment]
Ah yeah, my bad, it's `cargo install cargo-make`.

**Comment by rkfg** [comment]
It also needs `cargo install trunk`. After that I get:
```
error[E0308]: mismatched types
  --> app/src/main.rs:41:20
   |
40 | #[tokio::main]
   |              - help: consider removing this semicolon
41 | async fn main() -> Result<()> {
   |          ----      ^^^^^^^^^^ expected enum `Result`, found `()`
   |          |
   |          implicitly returns `()` as its body has no tail or `return` expression
   |
   = note:   expected enum `Result<(), anyhow::Error>`
           found unit type `()`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `app` due to previous error
[cargo-make] ERROR - Error while executing command, exit code: 101
[cargo-make] WARN - Build Failed.
```

**Comment by rkfg** [comment]
I'm not sure what I'm doing wrong but I decided to clean the repo using `git clean -fxd` to make sure there's no trash left from previous builds. Now I'm stuck at this:
```
error[E0599]: no method named `decode` found for reference `&'static Encoding` in the current scope
   --> src/unreal/deserializer.rs:146:42
    |
146 |                 if self.is_le { UTF_16LE.decode(&bytes) } else { UTF_16BE.decode(&bytes) };
    |                                          ^^^^^^ method not found in `&'static Encoding`

error[E0599]: no method named `decode` found for reference `&'static Encoding` in the current scope
   --> src/unreal/deserializer.rs:146:75
    |
146 |                 if self.is_le { UTF_16LE.decode(&bytes) } else { UTF_16BE.decode(&bytes) };
    |                                                                           ^^^^^^ method not found in `&'static Encoding`

error[E0599]: no method named `decode` found for reference `&'static Encoding` in the current scope
   --> src/unreal/deserializer.rs:157:57
    |
157 |             let (decoded, _, had_errors) = WINDOWS_1252.decode(&bytes);
    |                                                         ^^^^^^ method not found in `&'static Encoding`

error[E0599]: no method named `encode` found for reference `&'static Encoding` in the current scope
   --> src/unreal/serializer.rs:110:57
    |
110 |             let (encoded, _, had_errors) = WINDOWS_1252.encode(string);
    |                                                         ^^^^^^ method not found in `&'static Encoding`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `trilogy-save-editor` due to 4 previous errors
```
Same with `cargo build --release`.
